[tox]
envlist =
    ; Django 5.2, supported Wagtail versions (LTS + latest)
    py{310,311,312,313}-dj52-wt{70,73,74}
    ; Django 6.0, supported Wagtail versions (Django 6.0 support was added in Wagtail 7.3)
    py{312,313,314}-dj60-wt{73,74}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
commands = coverage run --parallel -m pytest -rs {posargs}
extras = test
deps =
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    wt70: wagtail>=7.0,<7.1
    wt73: wagtail>=7.3,<7.4
    wt74: wagtail>=7.4rc1,<7.5
    geoip2: geoip2

[testenv:future]
basepython = python3.14
extras = test
commands_pre =
    ; Test compatibility with development versions of Django and Wagtail.
    ; --no-deps stops pip from complaining about incompatible versions.
    pip install -U --no-deps \
        https://github.com/django/django/archive/refs/heads/main.zip \
        https://github.com/wagtail/wagtail/archive/refs/heads/main.zip
    pip freeze
commands = pytest -rs {posargs}

[testenv:coverage-report]
basepython = python3.12
deps = coverage
pip_pre = true
skip_install = true
commands =
    coverage report --include="src/**/" --omit="src/**/migrations/*.py"
