[tox]
envlist =
    flake8
    py310-dj42-wt41
    py310-dj42-wt51
    py{310,311,312,313,314}-dj{42}-wt{52}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
commands = coverage run --parallel -m pytest -rs {posargs}
extras = test
deps =
    dj32: Django>=3.2,<3.3
    dj41: Django>=4.1,<4.2
    dj42: Django>=4.2,<4.3
    wt41: wagtail>=4.1,<4.2
    wt51: wagtail>=5.1,<5.2
    wt52: wagtail>=5.2,<5.3
    geoip2: geoip2

[testenv:coverage-report]
basepython = python3.10
deps = coverage
pip_pre = true
skip_install = true
commands =
    coverage report --include="src/**/" --omit="src/**/migrations/*.py"

[testenv:lint]
basepython = python3.10
deps = flake8==3.5.0
commands =
    flake8 src tests setup.py
    isort --diff src/ tests/

[testenv:format]
basepython = python3.10
deps =
    isort
    black
skip_install = true
commands =
    black --check --exclude=/migrations setup.py src/wagtail_personalisation/ tests/
