# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_personalisation', '0008_devicerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('personalisablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_personalisation.PersonalisablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtail_personalisation.personalisablepage',),
        ),
    ]
