# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:36
from __future__ import unicode_literals

from django.db import migrations
from wagtail import VERSION as WAGTAIL_VERSION

import wagtail_personalisation

if WAGTAIL_VERSION >= (3, 0):
    from wagtail import blocks as wagtail_blocks
    from wagtail import fields as wagtail_fields
else:
    from wagtail.core import blocks as wagtail_blocks
    from wagtail.core import fields as wagtail_fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="intro",
            field=wagtail_fields.RichTextField(
                default='<p>Thank you for trying <a href="http://wagxperience.io" target="_blank">Wagxperience</a>!</p>'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail_fields.StreamField(
                (
                    (
                        "personalisable_paragraph",
                        wagtail_blocks.StructBlock(
                            (
                                (
                                    "segment",
                                    wagtail_blocks.ChoiceBlock(
                                        choices=wagtail_personalisation.blocks.list_segment_choices,
                                        help_text="Only show this content block for users in this segment",
                                        label="Personalisation segment",
                                        required=False,
                                    ),
                                ),
                                ("paragraph", wagtail_blocks.RichTextBlock()),
                            ),
                            icon="pilcrow",
                        ),
                    ),
                ),
                default="",
            ),
            preserve_default=False,
        ),
    ]
