# Generated by Django 3.2 on 2022-06-10 07:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail_personalisation.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('personalisable_paragraph', wagtail.blocks.StructBlock([('segment', wagtail.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choices, help_text='Only show this content block for users in this segment', label='Personalisation segment', required=False)), ('paragraph', wagtail.blocks.RichTextBlock())], icon='pilcrow'))], use_json_field=True),
        ),
    ]
