# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcountrule',
            name='operator',
            field=models.CharField(choices=[('more_than', 'More than'), ('less_than', 'Less than'), ('equal_to', 'Equal to')], default='more_than', max_length=20),
        ),
    ]
