# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0002_abstractbaserule_timerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractbaserule',
            name='segment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='personalisation.Segment'),
            preserve_default=False,
        ),
    ]
