# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0003_abstractbaserule_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('live', 'Live'), ('completed', 'Completed')], default='disabled', max_length=20),
        ),
    ]
