# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0004_segment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRule',
            fields=[
                ('abstractbaserule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalisation.AbstractBaseRule')),
                ('regex_string', models.TextField()),
            ],
            bases=('personalisation.abstractbaserule',),
        ),
    ]
