# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0004_segment_persistent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudfrontDeviceTypeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_smartphone', models.BooleanField(default=False)),
                ('is_desktop', models.BooleanField(default=False)),
                ('is_smarttv', models.BooleanField(default=False)),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalisation_cloudfrontdevicetyperule_related', related_query_name='personalisation_cloudfrontdevicetyperules', to='personalisation.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
