# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0004_segment_persistent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIsLoggedInRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_logged_in', models.BooleanField(default=False)),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalisation_userisloggedinrule_related', related_query_name='personalisation_userisloggedinrules', to='personalisation.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
