# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('personalisation', '0005_referralrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractbaserule',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_personalisation.abstractbaserule_set+', to='contenttypes.ContentType'),
        ),
    ]
