# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0008_auto_20161108_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled')], default='enabled', max_length=20),
        ),
    ]
