# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0009_auto_20161108_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractbaserule',
            name='name',
        ),
    ]
