# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0011_auto_20161109_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcountrule',
            name='count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
