# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0013_auto_20161109_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=20),
        ),
    ]
