# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0006_abstractbaserule_polymorphic_ctype'),
        ('personalisation', '0014_auto_20161109_1025'),
    ]

    operations = [
    ]
