# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0015_merge_20161109_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbaserule',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='personalisation.Segment'),
        ),
    ]
