# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0019_auto_20161109_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='disable_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='enable_date',
            field=models.DateTimeField(null=True),
        ),
    ]
