# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0020_auto_20161109_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbaserule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='personalisation.Segment'),
        ),
        migrations.AlterField(
            model_name='referralrule',
            name='regex_string',
            field=models.TextField(verbose_name='Regex string to match the referer with'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='disable_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='enable_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
