# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0022_visitcountrule_counted_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcountrule',
            name='counted_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
