# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('personalisation', '0023_auto_20161110_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalisablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('canonical_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='personalisation.PersonalisablePage')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='personalisation.Segment')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
