# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0024_personalisablepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalisablepage',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='personalisation.Segment'),
        ),
    ]
