# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 11:01
from __future__ import unicode_literals

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0025_auto_20161115_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractbaserule',
            name='segment',
        ),
        migrations.AddField(
            model_name='referralrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='referral_rules', to='personalisation.Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerule',
            name='segment',
            field=modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='time_rules', to='personalisation.Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitcountrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visit_count_rules', to='personalisation.Segment'),
            preserve_default=False,
        ),
    ]
