# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0026_auto_20161117_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractbaserule',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='abstractbaserule_ptr',
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='timerule',
            name='abstractbaserule_ptr',
        ),
        migrations.RemoveField(
            model_name='timerule',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='abstractbaserule_ptr',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='counted_page',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='segment',
        ),
        migrations.DeleteModel(
            name='AbstractBaseRule',
        ),
        migrations.DeleteModel(
            name='ReferralRule',
        ),
        migrations.DeleteModel(
            name='TimeRule',
        ),
        migrations.DeleteModel(
            name='VisitCountRule',
        ),
    ]
