# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:01
from __future__ import unicode_literals

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('personalisation', '0028_referralrule_timerule_visitcountrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_personalisation.abstractbaserule_set+', to='contenttypes.ContentType')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalisation_abstractbaserule_related', related_query_name='personalisation_abstractbaserules', to='personalisation.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='referral_rule_id',
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='timerule',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='timerule',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='timerule',
            name='time_rule_id',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='visit_count_rule_id',
        ),
        migrations.AddField(
            model_name='referralrule',
            name='abstractbaserule_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalisation.AbstractBaseRule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerule',
            name='abstractbaserule_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalisation.AbstractBaseRule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitcountrule',
            name='abstractbaserule_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalisation.AbstractBaseRule'),
            preserve_default=False,
        ),
    ]
