# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0029_auto_20161118_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalisablepage',
            name='is_segmented',
            field=models.BooleanField(default=False),
        ),
    ]
