# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 11:24
from __future__ import unicode_literals

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0030_personalisablepage_is_segmented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractbaserule',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='abstractbaserule',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='abstractbaserule_ptr',
        ),
        migrations.RemoveField(
            model_name='timerule',
            name='abstractbaserule_ptr',
        ),
        migrations.RemoveField(
            model_name='visitcountrule',
            name='abstractbaserule_ptr',
        ),
        migrations.AddField(
            model_name='referralrule',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personalisation_referralrule_related', related_query_name='personalisation_referralrules', to='personalisation.Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerule',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerule',
            name='segment',
            field=modelcluster.fields.ParentalKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personalisation_timerule_related', related_query_name='personalisation_timerules', to='personalisation.Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitcountrule',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitcountrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personalisation_visitcountrule_related', related_query_name='personalisation_visitcountrules', to='personalisation.Segment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AbstractBaseRule',
        ),
    ]
