# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0009_auto_20170531_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrule',
            name='regex_string',
            field=models.TextField(help_text='Enter the domain name (like google.com) or a regular expression to match the referrer', verbose_name='Referral'),
        ),
    ]
