# Generated by Django 1.11.6 on 2017-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        (
            "wagtail_personalisation",
            "0012_remove_personalisablepagemetadata_is_segmented",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="If this number is set for a static segment users will be added to the set until the number is reached. After this no more users will be added.",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="sessions",
            field=models.ManyToManyField(to="sessions.Session"),
        ),
        migrations.AddField(
            model_name="segment",
            name="type",
            field=models.CharField(
                choices=[("dynamic", "Dynamic"), ("static", "Static")],
                default="dynamic",
                help_text="\n            </br></br><strong>Dynamic:</strong> Automatically update the segment with new users that match the rules.\n            </br><strong>Static:</strong> Limit to users that pass segment rules when the segment is created.\n        ",
                max_length=20,
            ),
        ),
    ]
