# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0012_remove_personalisablepagemetadata_is_segmented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='status',
        ),
        migrations.AddField(
            model_name='segment',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Should the segment be active?'),
        ),
    ]
