# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0013_add_dynamic_static_to_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
    ]
