# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 16:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_personalisation", "0016_auto_20180125_0918"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="randomisation_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="If this number is set each user matching the rules will have this percentage chance of being placed in the segment.",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
