# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


def forward(apps, schema_editor):
    Segment = apps.get_model('wagtail_personalisation', 'Segment')

    for segment in Segment.objects.all():
        segment.enabled = segment.status == 'enabled'
        segment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0023_personalisablepagemetadata_variant_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Should the segment be active?'),
        ),
        migrations.RunPython(forward),
        migrations.RemoveField(
            model_name='segment',
            name='status',
        ),
    ]
